### ISSUE TITLE
Menu/Settings Add Delete Site option

### ISSUE THREAD

**Issue by kgilliam3662** [ConceptualSystems/library-sources#2]
when you click Menu/Settings and are presented with the Sites, there is no way to delete an
existing site.  I would recommend that you add a Del Site button next to New Site.

SITE Dropdown                         New Site    Del Site

Clicking Del Site will delete the current selected site.

**Comment by moonlightcheese** [comment]
Fixed in LIBS 1.0, Kitting 2.25, SMS Mobile 1.53
